const styles = {
  userMsg: {
    background:"#6949FF",
    width: "250px",
    borderTopLeftRadius: "25px",
    borderTopRightRadius: "25px",
    borderBottomRightRadius: "5px",
    borderBottomLeftRadius: "25px",
    paddingLeft: "16px",
    paddingTop: "24px",
    paddingRight: "10px",
    paddingBottom: "24px",
    gap: "10px",
    fontFamily: "Urbanist, sans-seriff",
    fontWeight: 400,
    fontSize: "18px",
    lineHeight: "25.2px",
    color: "#FFFFFF",
  },
  rexMsg: {
    background: "#F5F5F5",
    width: "250px",
    borderTopLeftRadius: "5px",
    borderTopRightRadius: "25px",
    borderBottomRightRadius: "25px",
    borderBottomLeftRadius: "25px",
    paddingLeft: "15px",
    paddingTop: "24px",
    paddingRight: "10px",
    paddingBottom: "24px",
    gap: "10px",
    fontFamily: "Urbanist, sans-seriff",
    fontWeight: 400,
    fontSize: "18px",
    lineHeight: "25.2px",
  },
};

export default styles;
